---

port: 4000
host: 0.0.0.0
safe: false
repository: CarstenKarbach/CarstenKarbach.github.io


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:       "Carsten Karbach"
keywords:    "Karbach, About, CV, projects"
description: "List of software projects developed by Carsten"
source_link: "https://github.com/CarstenKarbach/CarstenKarbach.github.io"
favicon:     "/img/favicon.ico"
touch_icon:  "/img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  grey: 	 '#999999'
  
kramdown:
  auto_ids:  false
  